QT       += core gui
TARGET = targettest
TEMPLATE = app
HEADERS += \
./Project/diskio.h\
./Project/ff.h\
./Project/ffconf.h\
./Project/lpc17xx_rtc.h\
./Project/lpc17xx_spi.h\
./Project/msc.h\
./Project/mscuser.h\
./Project/sd.h\
./Project/sdi.h\
./Project/spi.h\
./Project/type.h\
./Project/usb.h\
./Project/usbcfg.h\
./Project/usbcore.h\
./Project/usbdesc.h\
./Project/usbhw.h\
./Project/usbreg.h\
./Project/usbuser.h\
./doc/change_list.h\
./doc/store_list.h\
./inc/core_cm3.h\
./inc/diskio.h\
./inc/integer.h\
./inc/irq.h\
./inc/lpc17xx.h\
./inc/lpc17xx_uart.h\
./inc/system_LPC17xx.h\
./inc/type.h\
./inc/usbhost_uart.h\
./src/12UARTHandle/CAlarmBuffer.h\
./src/12UARTHandle/CComAnn.h\
./src/12UARTHandle/CComHandle.h\
./src/12UARTHandle/CComPara.h\
./src/12UARTHandle/CUartFun.h\
./src/12UARTHandle/CUartRcv.h\
./src/13CirCon/CAddressCount.h\
./src/14Sand195/CSendTo195.h\
./src/APP/Config.h\
./src/APP/include.h\
./src/APP/main.h\
./src/APP/publicparam.h\
./src/Board/CLED.h\
./src/Board/CRelay.h\
./src/Board/key.h\
./src/Board/lcd.h\
./src/Board/pcf8563.h\
./src/CLoopCtrl/CLpAnsCtrl.h\
./src/CLoopCtrl/CLpCkCtrl.h\
./src/CLoopCtrl/CLpInfoDef.h\
./src/CLoopCtrl/CLpScanCtrl.h\
./src/CNodeInfo/CNodeInfo.h\
./src/CRunCtrl/CRunCtrl.h\
./src/CRunCtrl/CSoftVerDef.h\
./src/CRunCtrl/CSysRunFlag.h\
./src/CTimeCtrl/CTimeCtrl.h\
./src/Hardware/CSSP/ssp.h\
./src/Hardware/Extint/extint.h\
./src/Hardware/GPIO/GPIOInit.h\
./src/Hardware/I2C/i2c.h\
./src/Hardware/IRQ/CGpioIrq.h\
./src/Hardware/Timer/CTime.h\
./src/Hardware/Timer/CTimeDef.h\
./src/Hardware/Timer/timer.h\
./src/Hardware/UART/uart.h\
./src/Hardware/Delay.h\
./src/Hardware/PWM.h\
./src/Menu/CAnnotate.h\
./src/Menu/CCompInten.h\
./src/Menu/CCompReg.h\
./src/Menu/CCompSet.h\
./src/Menu/CCompStat.h\
./src/Menu/CDateMod.h\
./src/Menu/CHistoryList.h\
./src/Menu/CLocalSet.h\
./src/Menu/CModelFault.h\
./src/Menu/CSysCheck.h\
./src/Menu/CSysReset.h\
./src/Menu/CTestSelf.h\
./src/Menu/alarmenu.h\
./src/Menu/batteryLow.h\
./src/Menu/breakdown.h\
./src/Menu/checkmenu.h\
./src/Menu/mainmenu.h\
./src/Menu/setmenu.h\
./src/Menu/startmenu.h\
./src/Menu/testmenu.h\
./src/MenuCtrl/CGetGrap.h\
./src/MenuCtrl/CKeyCounter.h\
./src/MenuCtrl/CTaskDown.h\
./src/MenuCtrl/CTaskReturn.h\
./src/MenuCtrl/CTaskSure.h\
./src/MenuCtrl/CTaskUp.h\
./src/MenuCtrl/runfunction.h\
./src/MenuCtrl/tasklist.h\
./src/common/16by16ziku.h\
./src/common/CFlashParam.h\
./src/common/CFlash_ADDR_Def.h\
./src/common/CGetCompSum.h\
./src/common/CGrapParam.h\
./src/common/CIntStEnd.h\
./src/common/CMaDefine.h\
./src/common/CSendToFlash.h\
./src/common/CSetCurrent.h\
./src/common/CSpeaker.h\
./src/common/CTimerTask.h\
./src/common/HZK16F.h\
./src/common/buffer.h\
./src/common/hzk12by12.h\
./src/common/hzk16by16 - 3500³£ÓÃºº×Ö.h\
./src/common/hzk16by16 - ËùÓÐºº×Ö.h\
./src/common/hzk16by16.h\
./src/common/ziku.h\
./src/componentinfo/componentinfo.h\
./src/componentinfo/store_addr.h\
./src/timesharectrl/SysCtrl.h\
./src/lpc177x_8x_uart.h\
./m25p80.h
SOURCES += \
./Project/Retarget.c\
./Project/Serial.c\
./Project/ccsbcs.c\
./Project/ff.c\
./Project/lpc17xx_rtc.c\
./Project/lpc17xx_spi.c\
./Project/mscuser.c\
./Project/sd.c\
./Project/sd1.c\
./Project/usbcore.c\
./Project/usbdesc.c\
./Project/usbhw.c\
./Project/usbuser.c\
./list/a.c\
./src/12UARTHandle/CAlarmBuffer.c\
./src/12UARTHandle/CComAnn.c\
./src/12UARTHandle/CComHandle.c\
./src/12UARTHandle/CComPara.c\
./src/12UARTHandle/CUartFun.c\
./src/12UARTHandle/CUartRcv.c\
./src/13CirCon/CAddressCount.c\
./src/14Sand195/CSendTo195.c\
./src/APP/main.c\
./src/Board/CLED.c\
./src/Board/CRelay.c\
./src/Board/key.c\
./src/Board/lcd.c\
./src/Board/pcf8563.c\
./src/CLoopCtrl/CLpAnsCtrl.c\
./src/CLoopCtrl/CLpCkCtrl.c\
./src/CLoopCtrl/CLpScanCtrl.c\
./src/CNodeInfo/CNodeInfo.c\
./src/CRunCtrl/CRunCtrl.c\
./src/CRunCtrl/CSysRunFlag.c\
./src/CTimeCtrl/CTimeCtrl.c\
./src/Hardware/CSSP/ssp.c\
./src/Hardware/Extint/extint.c\
./src/Hardware/I2C/i2c.c\
./src/Hardware/IRQ/CGpioIrq.c\
./src/Hardware/Timer/CTime.c\
./src/Hardware/Timer/CTimeDef.c\
./src/Hardware/Timer/timer.c\
./src/Hardware/UART/uart.c\
./src/Hardware/Delay.c\
./src/Hardware/PWM.c\
./src/Menu/CAnnotate.c\
./src/Menu/CCompInten.c\
./src/Menu/CCompReg.c\
./src/Menu/CCompSet.c\
./src/Menu/CCompStat.c\
./src/Menu/CDateMod.c\
./src/Menu/CHistoryList.c\
./src/Menu/CLocalSet.c\
./src/Menu/CModelFault.c\
./src/Menu/CSysCheck.c\
./src/Menu/CSysReset.c\
./src/Menu/CTestSelf.c\
./src/Menu/alarmenu.c\
./src/Menu/batteryLow.c\
./src/Menu/breakdown.c\
./src/Menu/checkmenu.c\
./src/Menu/mainmenu.c\
./src/Menu/setmenu.c\
./src/Menu/startmenu.c\
./src/Menu/testmenu.c\
./src/MenuCtrl/CGetGrap.c\
./src/MenuCtrl/CKeyCounter.c\
./src/MenuCtrl/CTaskDown.c\
./src/MenuCtrl/CTaskReturn.c\
./src/MenuCtrl/CTaskSure.c\
./src/MenuCtrl/CTaskUp.c\
./src/MenuCtrl/runfunction.c\
./src/MenuCtrl/tasklist.c\
./src/common/CFlashParam.c\
./src/common/CGetCompSum.c\
./src/common/CGrapParam.c\
./src/common/CIntStEnd.c\
./src/common/CSendToFlash.c\
./src/common/CSetCurrent.c\
./src/common/CSpeaker.c\
./src/common/CTimerTask.c\
./src/common/buffer.c\
./src/componentinfo/componentinfo.c\
./src/componentinfo/store_addr.c\
./src/timesharectrl/SysCtrl.c\
./src/core_cm3.c\
./src/lpc177x_8x_uart.c\
./src/system_LPC17xx.c\
./src/target.c\
./src/timer.c\
./m25p80.c
OTHER_FILES += \
./Annotation/CFlashParam.c.txt\
./Annotation/CTimeCtrl.c.txt\
./Project/output/139W.axf\
./Project/output/139W.hex\
./Project/output/139W.htm\
./Project/output/139W.lnp\
./Project/output/139W.plg\
./Project/output/139W.sct\
./Project/output/139W.tra\
./Project/output/139W_sct.Bak\
./Project/output/ExtDll.iex\
./Project/output/alarmenu.__i\
./Project/output/alarmenu.crf\
./Project/output/alarmenu.d\
./Project/output/alarmenu.o\
./Project/output/batterylow.__i\
./Project/output/batterylow.crf\
./Project/output/batterylow.d\
./Project/output/batterylow.o\
./Project/output/breakdown.__i\
./Project/output/breakdown.crf\
./Project/output/breakdown.d\
./Project/output/breakdown.o\
./Project/output/buffer.crf\
./Project/output/buffer.d\
./Project/output/buffer.o\
./Project/output/caddresscount.__i\
./Project/output/caddresscount.crf\
./Project/output/caddresscount.d\
./Project/output/caddresscount.o\
./Project/output/cannotate.__i\
./Project/output/cannotate.crf\
./Project/output/cannotate.d\
./Project/output/cannotate.o\
./Project/output/ccomann.__i\
./Project/output/ccomann.crf\
./Project/output/ccomann.d\
./Project/output/ccomann.o\
./Project/output/ccomhandle.__i\
./Project/output/ccomhandle.crf\
./Project/output/ccomhandle.d\
./Project/output/ccomhandle.o\
./Project/output/ccompara.__i\
./Project/output/ccompara.crf\
./Project/output/ccompara.d\
./Project/output/ccompara.o\
./Project/output/ccompinten.__i\
./Project/output/ccompinten.crf\
./Project/output/ccompinten.d\
./Project/output/ccompinten.o\
./Project/output/ccompreg.__i\
./Project/output/ccompreg.crf\
./Project/output/ccompreg.d\
./Project/output/ccompreg.o\
./Project/output/ccompset.crf\
./Project/output/ccompset.d\
./Project/output/ccompset.o\
./Project/output/ccompstat.__i\
./Project/output/ccompstat.crf\
./Project/output/ccompstat.d\
./Project/output/ccompstat.o\
./Project/output/cdatemod.crf\
./Project/output/cdatemod.d\
./Project/output/cdatemod.o\
./Project/output/cflashparam.__i\
./Project/output/cflashparam.crf\
./Project/output/cflashparam.d\
./Project/output/cflashparam.o\
./Project/output/cgetcompsum.crf\
./Project/output/cgetcompsum.d\
./Project/output/cgetcompsum.o\
./Project/output/cgetgrap.__i\
./Project/output/cgetgrap.crf\
./Project/output/cgetgrap.d\
./Project/output/cgetgrap.o\
./Project/output/cgpioirq.crf\
./Project/output/cgpioirq.d\
./Project/output/cgpioirq.o\
./Project/output/cgrapparam.crf\
./Project/output/cgrapparam.d\
./Project/output/cgrapparam.o\
./Project/output/checkmenu.__i\
./Project/output/checkmenu.crf\
./Project/output/checkmenu.d\
./Project/output/checkmenu.o\
./Project/output/chistorylist.__i\
./Project/output/chistorylist.crf\
./Project/output/chistorylist.d\
./Project/output/chistorylist.o\
./Project/output/cintstend.__i\
./Project/output/cintstend.crf\
./Project/output/cintstend.d\
./Project/output/cintstend.o\
./Project/output/ckeycounter.crf\
./Project/output/ckeycounter.d\
./Project/output/ckeycounter.o\
./Project/output/cled.crf\
./Project/output/cled.d\
./Project/output/cled.o\
./Project/output/clocalset.__i\
./Project/output/clocalset.crf\
./Project/output/clocalset.d\
./Project/output/clocalset.o\
./Project/output/clpansctrl.crf\
./Project/output/clpansctrl.d\
./Project/output/clpansctrl.o\
./Project/output/clpckctrl.crf\
./Project/output/clpckctrl.d\
./Project/output/clpckctrl.o\
./Project/output/clpscanctrl.crf\
./Project/output/clpscanctrl.d\
./Project/output/clpscanctrl.o\
./Project/output/cmodelfault.__i\
./Project/output/cmodelfault.crf\
./Project/output/cmodelfault.d\
./Project/output/cmodelfault.o\
./Project/output/cnodeinfo.crf\
./Project/output/cnodeinfo.d\
./Project/output/cnodeinfo.o\
./Project/output/componentinfo.crf\
./Project/output/componentinfo.d\
./Project/output/componentinfo.o\
./Project/output/core_cm3.crf\
./Project/output/core_cm3.d\
./Project/output/core_cm3.o\
./Project/output/crelay.__i\
./Project/output/crelay.crf\
./Project/output/crelay.d\
./Project/output/crelay.o\
./Project/output/crunctrl.__i\
./Project/output/crunctrl.crf\
./Project/output/crunctrl.d\
./Project/output/crunctrl.o\
./Project/output/csendto195.__i\
./Project/output/csendto195.crf\
./Project/output/csendto195.d\
./Project/output/csendto195.o\
./Project/output/csendtoflash.crf\
./Project/output/csendtoflash.d\
./Project/output/csendtoflash.o\
./Project/output/csetcurrent.__i\
./Project/output/csetcurrent.crf\
./Project/output/csetcurrent.d\
./Project/output/csetcurrent.o\
./Project/output/cspeaker.__i\
./Project/output/cspeaker.crf\
./Project/output/cspeaker.d\
./Project/output/cspeaker.o\
./Project/output/csyscheck.__i\
./Project/output/csyscheck.crf\
./Project/output/csyscheck.d\
./Project/output/csyscheck.o\
./Project/output/csysreset.__i\
./Project/output/csysreset.crf\
./Project/output/csysreset.d\
./Project/output/csysreset.o\
./Project/output/csysrunflag.crf\
./Project/output/csysrunflag.d\
./Project/output/csysrunflag.o\
./Project/output/ctaskdown.__i\
./Project/output/ctaskdown.crf\
./Project/output/ctaskdown.d\
./Project/output/ctaskdown.o\
./Project/output/ctaskreturn.__i\
./Project/output/ctaskreturn.crf\
./Project/output/ctaskreturn.d\
./Project/output/ctaskreturn.o\
./Project/output/ctasksure.__i\
./Project/output/ctasksure.crf\
./Project/output/ctasksure.d\
./Project/output/ctasksure.o\
./Project/output/ctaskup.__i\
./Project/output/ctaskup.crf\
./Project/output/ctaskup.d\
./Project/output/ctaskup.o\
./Project/output/ctestself.crf\
./Project/output/ctestself.d\
./Project/output/ctestself.o\
./Project/output/ctime.__i\
./Project/output/ctime.crf\
./Project/output/ctime.d\
./Project/output/ctime.o\
./Project/output/ctimectrl.__i\
./Project/output/ctimectrl.crf\
./Project/output/ctimectrl.d\
./Project/output/ctimectrl.o\
./Project/output/ctimedef.crf\
./Project/output/ctimedef.d\
./Project/output/ctimedef.o\
./Project/output/ctimertask.__i\
./Project/output/ctimertask.crf\
./Project/output/ctimertask.d\
./Project/output/ctimertask.o\
./Project/output/cuart.__i\
./Project/output/cuart.d\
./Project/output/cuartfun.__i\
./Project/output/cuartfun.crf\
./Project/output/cuartfun.d\
./Project/output/cuartrcv.__i\
./Project/output/cuartrcv.d\
./Project/output/delay.__i\
./Project/output/delay.crf\
./Project/output/delay.d\
./Project/output/delay.o\
./Project/output/extint.__i\
./Project/output/extint.crf\
./Project/output/extint.d\
./Project/output/extint.o\
./Project/output/gpioinit.crf\
./Project/output/gpioinit.d\
./Project/output/gpioinit.o\
./Project/output/i2c.__i\
./Project/output/i2c.crf\
./Project/output/i2c.d\
./Project/output/i2c.o\
./Project/output/key.__i\
./Project/output/key.crf\
./Project/output/key.d\
./Project/output/key.o\
./Project/output/lcd.crf\
./Project/output/lcd.d\
./Project/output/lcd.o\
./Project/output/lpc177x_8x_uart.__i\
./Project/output/lpc177x_8x_uart.d\
./Project/output/main.__i\
./Project/output/main.crf\
./Project/output/main.d\
./Project/output/main.o\
./Project/output/mainmenu.__i\
./Project/output/mainmenu.crf\
./Project/output/mainmenu.d\
./Project/output/mainmenu.o\
./Project/output/pcf8563.__i\
./Project/output/pcf8563.crf\
./Project/output/pcf8563.d\
./Project/output/pcf8563.o\
./Project/output/pwm.__i\
./Project/output/pwm.crf\
./Project/output/pwm.d\
./Project/output/pwm.o\
./Project/output/runfunction.__i\
./Project/output/runfunction.crf\
./Project/output/runfunction.d\
./Project/output/runfunction.o\
./Project/output/setmenu.__i\
./Project/output/setmenu.crf\
./Project/output/setmenu.d\
./Project/output/setmenu.o\
./Project/output/ssp.crf\
./Project/output/ssp.d\
./Project/output/ssp.o\
./Project/output/startmenu.__i\
./Project/output/startmenu.crf\
./Project/output/startmenu.d\
./Project/output/startmenu.o\
./Project/output/startup_LPC17xx.d\
./Project/output/startup_LPC17xx.o\
./Project/output/store_addr.__i\
./Project/output/store_addr.crf\
./Project/output/store_addr.d\
./Project/output/store_addr.o\
./Project/output/sysctrl.__i\
./Project/output/sysctrl.crf\
./Project/output/sysctrl.d\
./Project/output/sysctrl.o\
./Project/output/system_lpc17xx.crf\
./Project/output/system_lpc17xx.d\
./Project/output/system_lpc17xx.o\
./Project/output/tasklist.__i\
./Project/output/tasklist.crf\
./Project/output/tasklist.d\
./Project/output/tasklist.o\
./Project/output/testmenu.__i\
./Project/output/testmenu.crf\
./Project/output/testmenu.d\
./Project/output/testmenu.o\
./Project/output/uart.__i\
./Project/output/uart.crf\
./Project/output/uart.d\
./Project/output/uart.o\
./Project/JLinkArm_usb_disk_test.ini\
./Project/JLinkLog.txt\
./Project/JLinkSettings.ini\
./Project/QQ½ØÍ¼Î´ÃüÃû.jpg\
./Project/usb_disk_test.uvgui.Administrator\
./Project/usb_disk_test.uvgui.Owner\
./Project/usb_disk_test.uvgui.grant\
./Project/usb_disk_test.uvgui.lenovo\
./Project/usb_disk_test.uvgui.xiaoweilai\
./Project/usb_disk_test.uvgui_xiaoweilai.bak\
./Project/usb_disk_test.uvopt\
./Project/usb_disk_test.uvproj\
./Project/usb_disk_test_usb_disk_test.dep\
./Project/usb_disk_test_uvopt.bak\
./Project/usb_disk_test_uvproj.bak\
./SI/139.IAB\
./SI/139.IAD\
./SI/139.IMB\
./SI/139.IMD\
./SI/139.PFI\
./SI/139.PO\
./SI/139.PR\
./SI/139.PRI\
./SI/139.PS\
./SI/139.SearchResults\
./SI/139.WK3\
./list/139W.map\
./list/alarmenu._ip\
./list/alarmenu.i\
./list/batterylow._ip\
./list/batterylow.i\
./list/breakdown._ip\
./list/breakdown.i\
./list/buffer._ip\
./list/buffer.i\
./list/caddresscount._ip\
./list/caddresscount.i\
./list/cannotate._ip\
./list/cannotate.i\
./list/ccomann._ip\
./list/ccomann.i\
./list/ccomhandle._ip\
./list/ccomhandle.i\
./list/ccompara._ip\
./list/ccompara.i\
./list/ccompinten._ip\
./list/ccompinten.i\
./list/ccompreg._ip\
./list/ccompreg.i\
./list/ccompset._ip\
./list/ccompset.i\
./list/ccompstat._ip\
./list/ccompstat.i\
./list/cdatemod._ip\
./list/cdatemod.i\
./list/cflashparam._ip\
./list/cflashparam.i\
./list/cgetcompsum.i\
./list/cgetgrap._ip\
./list/cgetgrap.i\
./list/cgpioirq.i\
./list/cgrapparam._ip\
./list/cgrapparam.i\
./list/checkmenu._ip\
./list/checkmenu.i\
./list/chistorylist._ip\
./list/chistorylist.i\
./list/cintstend._ip\
./list/cintstend.i\
./list/ckeycounter.i\
./list/cled.i\
./list/clocalset._ip\
./list/clocalset.i\
./list/clpansctrl.i\
./list/clpckctrl.i\
./list/clpscanctrl.i\
./list/cmodelfault._ip\
./list/cmodelfault.i\
./list/cnodeinfo.i\
./list/componentinfo.i\
./list/core_cm3.i\
./list/crelay._ip\
./list/crelay.i\
./list/crunctrl._ip\
./list/crunctrl.i\
./list/csendto195._ip\
./list/csendto195.i\
./list/csendtoflash.i\
./list/csetcurrent._ip\
./list/csetcurrent.i\
./list/cspeaker._ip\
./list/cspeaker.i\
./list/csyscheck._ip\
./list/csyscheck.i\
./list/csysreset._ip\
./list/csysreset.i\
./list/csysrunflag.i\
./list/ctaskdown._ip\
./list/ctaskdown.i\
./list/ctaskreturn._ip\
./list/ctaskreturn.i\
./list/ctasksure._ip\
./list/ctasksure.i\
./list/ctaskup._ip\
./list/ctaskup.i\
./list/ctestself._ip\
./list/ctestself.i\
./list/ctime._ip\
./list/ctime.i\
./list/ctimectrl._ip\
./list/ctimectrl.i\
./list/ctimedef.i\
./list/ctimertask._ip\
./list/ctimertask.i\
./list/cuart._ip\
./list/cuart.i\
./list/cuartfun._ip\
./list/cuartfun.i\
./list/cuartrcv._ip\
./list/cuartrcv.i\
./list/delay._ip\
./list/delay.i\
./list/extint._ip\
./list/extint.i\
./list/gpioinit.i\
./list/i2c._ip\
./list/i2c.i\
./list/key._ip\
./list/key.i\
./list/lcd.i\
./list/lpc177x_8x_uart._ip\
./list/lpc177x_8x_uart.i\
./list/main._ip\
./list/main.i\
./list/mainmenu._ip\
./list/mainmenu.i\
./list/pcf8563._ip\
./list/pcf8563.i\
./list/pwm._ip\
./list/pwm.i\
./list/runfunction._ip\
./list/runfunction.i\
./list/setmenu._ip\
./list/setmenu.i\
./list/ssp.i\
./list/startmenu._ip\
./list/startmenu.i\
./list/startup_LPC17xx.lst\
./list/store_addr._ip\
./list/store_addr.i\
./list/sysctrl._ip\
./list/sysctrl.i\
./list/system_lpc17xx.i\
./list/tasklist._ip\
./list/tasklist.i\
./list/testmenu._ip\
./list/testmenu.i\
./list/uart._ip\
./list/uart.i\
./list/usb_disk_test.map\
./src/12UARTHandle/CUartFun.h.bak\
./src/Hardware/GPIO/GPIOInit.C\
./src/startup_LPC17xx.s\
./FuncNoteV1.2.4.1.exe\
./LPC1768_V1_6.pro.user\
./LPC1768_V1_7.pro\
./LPC1768_V1_7.pro.user\
./README.md\
./Readme.txt\
./findcandcpptolist.R.exe\
./fun_Annotation.txt\
./gasproject_LPC1768_V1_7.pro\
./head_Annotation.txt\
./keilkill.bat


INCLUDEPATH +=\
./Annotation\
./Project\
./Project/output\
./SI\
./doc\
./inc\
./list\
./src\
./src/12UARTHandle\
./src/13CirCon\
./src/14Sand195\
./src/APP\
./src/Board\
./src/CLoopCtrl\
./src/CNodeInfo\
./src/CRunCtrl\
./src/CTimeCtrl\
./src/Hardware\
./src/Hardware/CSSP\
./src/Hardware/Extint\
./src/Hardware/GPIO\
./src/Hardware/I2C\
./src/Hardware/IRQ\
./src/Hardware/Timer\
./src/Hardware/UART\
./src/Menu\
./src/MenuCtrl\
./src/common\
./src/componentinfo\
./src/timesharectrl
